# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-05 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackActivity', '0002_auto_20200804_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
